# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Base box to use
  config.vm.box = "hashicorp/precise64"

  # Enables guest ssh to use host ssh configuration
  config.ssh.forward_agent = true

  # VirtualBox configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Hotsmanager configuration (port forwarding)
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.define 'example-box' do |node|
    node.vm.hostname = 'example'
    node.vm.network :private_network, ip: '192.168.42.42'
  end

  # Set a proper shell
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  # Provisions for environment configuration
  config.vm.provision "example", type: "shell", path: "bootstrap.sh", privileged: false
end